name: dpkg
version: 0.0.1

description:
  Debian Package library

homepage: https://github.com/canonical/dpkg.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.1.2

# XZ support not yet in a released version
dependency_overrides:
 archive:
  git:
    url: git@github.com:brendan-duncan/archive.git

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8
